{
 "title": "MongoDB Performance Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "hostname",
    "query": "SHOW TAG VALUES FROM \"mongodb\" WITH KEY=\"hostname\""
   }
  ]
 },
 "panels": [
  {
   "title": "Health state",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replica set member state",
     "type": "stat",
     "description": "https://www.mongodb.com/docs/manual/reference/replica-states/",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_hostname | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "repl_state" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_hostname | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "uptime_ns" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "General performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operations | $hostname",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "command | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "commands" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "insert | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "inserts" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "query | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "queries" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "update | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "updates" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "delete | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "deletes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "getmore | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "getmores" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Active Read & Write | Queued Read & Write | $hostname",
     "type": "timeseries",
     "description": "Queues describe the number of operations waiting for a lock, either read or write. High queues may indicate the existence of conflicting writing paths or suboptimal schema design, which force high competition over database resources. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "active read | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "active_reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "active write | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "active_writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "queued read | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "queued_reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "queued write | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "queued_writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Latency Read & Write | $hostname",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "alias": "read | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "query": "SELECT non_negative_derivative(mean(\"latency_reads\"), 1s) / non_negative_derivative(mean(\"latency_reads_count\"), 1s) FROM \"mongodb\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"hostname\", \"node_type\", \"rs_name\" fill(null)",
       "select": [
        [
         { "params": [ "latency_reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "write | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "query": "SELECT non_negative_derivative(mean(\"latency_writes\"), 1s)  / non_negative_derivative(mean(\"latency_writes_count\"), 1s) FROM \"mongodb\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"hostname\", \"node_type\", \"rs_name\" fill(null)",
       "select": [
        [
         { "params": [ "latency_writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Scanned Objects / Returned & Scanned / Returned | $hostname",
     "type": "timeseries",
     "description": "Scanned objects displays the number of documents scanned per second. Scanned displays the number of index items scanned per second. The ratio between the number of documents scanned and the number of documents returned. A high number ratio may indicate suboptimal operations which scan a lot of documents to return a smaller portion.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Scanned Objects / Returned | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "query": "SELECT non_negative_derivative(mean(\"total_docs_scanned\"), 1s) / non_negative_derivative(mean(\"document_returned\"), 1s) FROM \"mongodb\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"hostname\", \"node_type\", \"rs_name\" fill(null)",
       "select": [
        [
         { "params": [ "total_docs_scanned" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "Scanned / Returned | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "query": "SELECT non_negative_derivative(mean(\"total_keys_scanned\"), 1s) / non_negative_derivative(mean(\"document_returned\"), 1s) FROM \"mongodb\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"hostname\", \"node_type\", \"rs_name\" fill(null)",
       "select": [
        [
         { "params": [ "total_docs_scanned" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Scan and Order | $hostname",
     "type": "timeseries",
     "description": "This refers to the average rate per second over the selected sample period of queries that return sorted results that cannot perform the sort operation using an index.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "operation_scan_and_order" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Bytes In & Bytes Out | $hostname",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "bytes in | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "net_in_bytes_count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "bytes out | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "net_out_bytes_count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Resource utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections Used | $hostname",
     "type": "stat",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_hostname | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "query": "SELECT (last(\"connections_current\") * 100) / (last(\"connections_available\") + last(\"connections_current\")) FROM \"mongodb\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"hostname\",\"node_type\",\"rs_name\" fill(null)",
       "select": [
        [
         { "params": [ "connections_available" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "connections_current" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Connections Used | $hostname",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 16, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_hostname | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "query": "SELECT (last(\"connections_current\") * 100) / (last(\"connections_available\") + last(\"connections_current\")) FROM \"mongodb\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"hostname\",\"node_type\",\"rs_name\" fill(null)",
       "select": [
        [
         { "params": [ "connections_available" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "connections_current" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Connections | $hostname",
     "type": "timeseries",
     "description": "This describes the number of open connections to the instance. High numbers or spikes might indicate a suboptimal connection strategy from the client side or unresponsive server.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "current | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "connections_current" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "available | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "connections_available" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory | $hostname",
     "type": "timeseries",
     "description": "Resident memory - Amount of memory used by the database process.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "alias": "resident | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "resident_megabytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "virtual | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "vsize_megabytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Page fault | $hostname",
     "type": "timeseries",
     "description": "Page faults indicate operations which required the MongoDB to fetch data from disk because it wasn’t available in active memory",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "page fault | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "page_faults" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Replication and Oplog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replication lag | $hostname",
     "type": "timeseries",
     "description": "Replication lag is the approximate number of seconds a secondary node is behind the primary in write operations. High replication lag will indicate a secondary that struggles to replicate and might influence your operations' latency considering the write/read concern of the connections.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "lag time | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "repl_lag" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Oplog window | $hostname",
     "type": "timeseries",
     "description": "This is the approximate number of hours available in the primary's replication oplog. If a secondary is lagging more than this amount, it cannot catch up and will require a full resync.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "alias": "window repl oplog | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "repl_oplog_window_sec" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Errors: asserts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors: asserts | $hostname",
     "type": "timeseries",
     "description": "While assert errors are typically uncommon, if there are non-zero values for the asserts, you should examine the log file for more information. In many cases, these errors are trivial, but are worth investigating.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "assert_msg | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "assert_msg" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "assert_regular | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "assert_regular" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "assert_rollovers | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "assert_rollovers" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "assert_user | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "assert_user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "assert_warning | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "assert_warning" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}