{
 "title": "MongoDB Performance Monitoring v2",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "hostname",
    "query": "SHOW TAG VALUES FROM \"mongodb\" WITH KEY=\"hostname\""
   },
   {
    "name": "db_name",
    "label": "db_name",
    "query": "SHOW TAG VALUES FROM \"mongodb_db_stats\" WITH KEY=\"db_name\""
   }
  ]
 },
 "panels": [
  {
   "title": "Operations | $hostname",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "command | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "commands" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "insert | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "inserts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "query | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "queries" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "update | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "updates" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "delete | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "deletes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "getmore | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "getmores" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Latency Read & Write | $hostname",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "read | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "query": "SELECT non_negative_derivative(mean(\"latency_reads\"), 1s) / non_negative_derivative(mean(\"latency_reads_count\"), 1s) FROM \"mongodb\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"hostname\", \"node_type\", \"rs_name\" fill(null)",
     "select": [
      [
       { "params": [ "latency_reads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "write | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "query": "SELECT non_negative_derivative(mean(\"latency_writes\"), 1s)  / non_negative_derivative(mean(\"latency_writes_count\"), 1s) FROM \"mongodb\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"hostname\", \"node_type\", \"rs_name\" fill(null)",
     "select": [
      [
       { "params": [ "latency_writes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Read & Write | Queued Read & Write | $hostname",
   "type": "timeseries",
   "description": "Queues describe the number of operations waiting for a lock, either read or write. High queues may indicate the existence of conflicting writing paths or suboptimal schema design, which force high competition over database resources. ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "active read | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "active_reads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "active write | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "active_writes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "queued read | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "queued_reads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "queued write | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "queued_writes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Scan and Order | $hostname",
   "type": "timeseries",
   "description": "<li>A high Scan and Order number indicates that the server is having to sort query results to get them in the right order. This takes time and increases the memory load on the server.\n<li>Fix this by making sure indexes are sorted in the order in which the queries need the documents, or by adding missing indexes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "operation_scan_and_order" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Scanned Objects / Returned & Scanned / Returned | $hostname",
   "type": "timeseries",
   "description": "<u>Scanned objects/returned</u> is the number of documents scanned versus the number returned. A large number is a sign that you may need an index on the fields you are querying on.<br>\n<u>Scanned/returned</u> refers to the ratio between the number of index items scanned and the number of documents returned by queries. If this value is 1.0, then your query scanned exactly as many index items as documents it returned – it’s an efficient query.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Scanned Objects / Returned | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "query": "SELECT non_negative_derivative(mean(\"total_docs_scanned\"), 1s) / non_negative_derivative(mean(\"document_returned\"), 1s) FROM \"mongodb\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"hostname\", \"node_type\", \"rs_name\" fill(null)",
     "select": [
      [
       { "params": [ "total_docs_scanned" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Scanned / Returned | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "query": "SELECT non_negative_derivative(mean(\"total_keys_scanned\"), 1s) / non_negative_derivative(mean(\"document_returned\"), 1s) FROM \"mongodb\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"hostname\", \"node_type\", \"rs_name\" fill(null)",
     "select": [
      [
       { "params": [ "total_docs_scanned" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Replication lag | $hostname",
   "type": "timeseries",
   "description": "<u>Replication lag</u> occurs when a secondary member of a replica set falls behind the primary. High replication lag will indicate a secondary that struggles to replicate and might influence your operations' latency considering the write/read concern of the connections.\n<li>A networking issue between the primary and secondary, making nodes unreachable\n<li>A secondary node applying data slower than the primary node\n<li>Insufficient write capacity in which case you should add more shards\n<li>Slow operations on the primary node, blocking replication",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "repl_lag" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "WiredTiger Ticket Number | $hostname",
   "type": "timeseries",
   "description": "<u>WiredTiger Ticket Number</u> is a key indicator of the performance of the WiredTiger storage engine.\n<li>WiredTiger has a concept of read or write tickets that are created when the database is accessed. The WiredTiger ticket number should always be at 128.\n<li>If the value goes below 128 and stays below that number, that means the server is waiting on something and it's an indication of a problem.\n<li>The remedy is then to find the operations that are going too slowly and start a debugging process.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "read | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "total_tickets_reads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "write | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "total_tickets_writes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Bytes In & Bytes Out | $hostname",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "bytes in | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "net_in_bytes_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "bytes out | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "net_out_bytes_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of open cursors | $hostname",
   "type": "timeseries",
   "description": "<u>Number of open cursors</u> rising without a corresponding growth of traffic is often symptomatic of poorly indexed queries or the result of long running queries due to large result sets.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "cursor_no_timeout_count | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "cursor_no_timeout_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "cursor_pinned_count | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "cursor_pinned_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "cursor_timed_out_count | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "cursor_timed_out_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "cursor_total_count | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "cursor_total_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Connections | $hostname",
   "type": "timeseries",
   "description": "This describes the number of open connections to the instance. High numbers or spikes might indicate a suboptimal connection strategy from the client side or unresponsive server.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "current | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "connections_current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "available | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "connections_available" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Connections Used % | $hostname",
   "type": "timeseries",
   "description": "Percentage of connections used, can indicate when MongoDB is getting close to running out of available connections.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "query": "SELECT (last(\"connections_current\") * 100) / (last(\"connections_available\") + last(\"connections_current\")) FROM \"mongodb\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"hostname\",\"node_type\",\"rs_name\" fill(null)",
     "select": [
      [
       { "params": [ "connections_available" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "connections_current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Page fault | $hostname",
   "type": "timeseries",
   "description": "Page faults indicate operations which required the MongoDB to fetch data from disk because it wasn’t available in active memory",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "page fault | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "page_faults" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage metrics | Size | $db_name | $hostname",
   "type": "timeseries",
   "description": "<u>Storage metrics</u> track how MongoDB is using persistent storage. In the WiredTiger storage engine, each collection is a file and so is each index. When a document in a collection is updated, the entire document is re-written.\n\n<li>If memory space metrics (data, index, or storage) or the number of objects show a significant unexpected change while the database traffic stays within ordinary ranges, it can indicate a problem.\n<li>A sudden drop in dataSize may indicate a large amount of data deletion, which should be quickly investigated if it was not expected.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "data | $tag_db_name | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "db_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb_db_stats",
     "select": [
      [
       { "params": [ "data_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "db_name", "operator": "=~", "value": "/^$db_name$/" }
     ]
    },
    {
     "alias": "storage | $tag_db_name | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "db_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb_db_stats",
     "select": [
      [
       { "params": [ "storage_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "db_name", "operator": "=~", "value": "/^$db_name$/" }
     ]
    },
    {
     "alias": "index | $tag_db_name | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "db_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb_db_stats",
     "select": [
      [
       { "params": [ "index_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "db_name", "operator": "=~", "value": "/^$db_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache used % | $hostname",
   "type": "timeseries",
   "description": "<u>Cache metrics</u> can help determine if the working set is outgrowing the available cache.\n<li>A growing amount of dirty data — data changed but not yet written to disk — can indicate problems related to the amount of memory available.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "dirty | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "percent_cache_dirty" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "used | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "percent_cache_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory | $hostname",
   "type": "timeseries",
   "description": "Resident memory - Amount of memory used by the database process.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "resident | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "resident_megabytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "virtual | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "vsize_megabytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors: asserts | $hostname",
   "type": "timeseries",
   "description": "<li>While assert errors are typically uncommon, if there are non-zero values for the asserts, you should examine the log file for more information. In many cases, these errors are trivial, but are worth investigating.\n<li>Monitoring the number of asserts created at various levels of severity can provide a first level indication of unexpected problems. Asserts can be message asserts, the most serious kind, or warning assets, regular asserts, and user asserts.\n<li> <u>Regular asserts</u> are per-operation variants (eg., \"unexpected failure while reading a BSON document\"). \n<li> <u>Warning asserts</u> are not as serious as errors. They just indicate conditions that might be worth checking like too low ulimit or readahead. \n<li> <u>Message asserts</u> indicate internal server exceptions. \n<li> <u>User asserts</u> are triggered as the result of user operations or commands generating an error like a full disk space, a duplicate key exception, or write errors (e.g. insert not properly formatted, or no access right). These errors are returned to the client so most of them won’t be logged into the mongod logs. However you should investigate potential problems with your application or deployment.\nBoth regular and user asserts will result in the corresponding operation failing.\n<li> <u>Rollover asserts</u> is the number of times that the rollover counters have rolled over since the last time the MongoDB process started. The counters will rollover to zero after 230 assertions. Use this value to provide context to the other values reported by the test.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "assert_msg | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "assert_msg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "assert_regular | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "assert_regular" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "assert_rollovers | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "assert_rollovers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "assert_user | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "assert_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "assert_warning | $tag_hostname | $tag_node_type | $tag_rs_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "node_type" ], "type": "tag" },
      { "params": [ "rs_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mongodb",
     "select": [
      [
       { "params": [ "assert_warning" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Health state",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replica set member state",
     "type": "stat",
     "description": "https://www.mongodb.com/docs/manual/reference/replica-states/",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 73 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_hostname | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "repl_state" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_hostname | $tag_hostname | $tag_node_type | $tag_rs_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "node_type" ], "type": "tag" },
        { "params": [ "rs_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "uptime_ns" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}